version: 2.1

jobs:
  chd_:
    description: A job that says Hello
    machine: true
    steps:
      - run: echo "Hello Worldd!"

jobs:
  checkoutyo:
    description: A job that sfffays Hello
    machine: true
    steps:
      - run: echo "Helslo Worldd!"

workflows:
  monWorkflow:
    jobs:
      -chd_
      -checkoutyo
