version: 2.1

jobs:
  checkout_and_unit_test:
    description: A job that says Hello
    machine: true
    steps:
      - run: echo "Hello Worldd!"
  deploy_backend:
    description: A job that sfffays Hello
    machine: true
    steps:
      - run: echo "Helslo Worldd!"
  integration_tests_backend:
    description: A job that sfffays Hello
    machine: true
    steps:
      - run: echo "Helslo Worldd!"
  deploy_staging:
    description: A job that sfffays Hello
    machine: true
    steps:
      - run: echo "Helslo Worldd!"
  acceptance_test_1:
    description: A job that sfffays Hello
    machine: true
    steps:
      - run: echo "Helslo Worldd!"
  acceptance_test_2:
    description: A job that sfffays Hello
    machine: true
    steps:
      - run: echo "Helslo Worldd!"
  acceptance_test_3:
    description: A job that sfffays Hello
    machine: true
    steps:
      - run: echo "Helslo Worldd!"
  acceptance_test_4:
    description: A job that sfffays Hello
    machine: true
    steps:
      - run: echo "Helslo Worldd!"
  deploy_production:
    description: A job that sfffays Hello
    machine: true
    steps:
      - run: echo "Helslo Worldd!"


workflows:
  monWorkflow:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
        requires: 
          - checkout_and_unit_test
